name: 'Setup gpg'
description: 'Load public keys'
inputs:
  kids:
    description: 'kids to fetch'
    required: true
    default: '9682378BBACEEDD1'
runs:
  using: "composite"
  steps:
    - shell: bash 
      run: |
        for kid in ${{ inputs.kids}}
        do
          gpg -a --output $kid.pub --export $kid
          gpg --import $kid.pub
        end
        
